version: 2.1

experimental:
  notify:
    branches:
      only:
        - master
        - v5
        - v6

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.15
          docker-image: cimg/go:1.15.2
          run-lint: true
          test-coverage: true
      - go-test:
          name: Go 1.14
          docker-image: cimg/go:1.14.9
      - integration-test
      - test-publish
      - publish:
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-.*)?/
            branches:
              only: /v\d+/
          requires:
            - Go 1.14

  # Run hourly integration tests on the private v6 branch
  hourly-integration-test:
    triggers:
    - schedule:
        cron: "0 * * * *"
        filters:
          branches:
            only: v6
    jobs:
      - integration-test
    when:
      equal: ["https://github.com/launchdarkly/ld-relay-private", <<pipeline.project.git_url>>]

jobs:
  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
      test-coverage:
        type: boolean
        default: false
    
    docker:
      - image: <<parameters.docker-image>>
        environment: &environment
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts
          COMMON_GO_PACKAGES: >
            github.com/jstemmer/go-junit-report

    steps:
      - checkout
      - run: go get -u $COMMON_GO_PACKAGES
      - run: go version && go env
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_ARTIFACTS
      - unless:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests
                command: make test | tee $CIRCLE_ARTIFACTS/report.txt  
            - run:
                name: Process test results
                command: go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml
                when: always
      - when:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests with coverage
                command: make test-coverage
            - run:
                name: Store coverage results
                command: cp build/coverage* /tmp/circle-artifacts
                when: always
      - run:
          name: Run Prometheus endpoint test
          command: ./scripts/test-prometheus-endpoint.sh
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts

  integration-test:
    machine: # can't use regular Docker mode because we need to run our own Docker containers and share files with them
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    environment: &environment
      CIRCLE_TEST_REPORTS: /tmp/circle-reports
      CIRCLE_ARTIFACTS: /tmp/circle-artifacts
      COMMON_GO_PACKAGES: >
        github.com/jstemmer/go-junit-report
    steps:
      - checkout
      - run:
          name: install Go # since we're using machine mode, we can't use a preinstalled Go Docker image
          command: |
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:longsleep/golang-backports
            sudo apt update
            sudo apt install -y golang-go
      - run: go version && go env
      - restore_cache:
          keys: 
            - deps-relay-i9ntest-{{ checksum "go.mod" }}    
      - run: go get -u $COMMON_GO_PACKAGES
      - run: go test -t integrationtests -i ./integrationtests # just install the dependencies for the tests
      - save_cache:
          key: deps-relay-i9ntest-{{ checksum "go.mod" }}    
          paths:
            - /home/circleci/.go_workspace
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: Run integration tests
          command: make integration-test | tee $CIRCLE_ARTIFACTS/report.txt
      - run:
          name: Process test results
          command: go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml
          when: always
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts
        
  test-publish:
    docker:
      - &release_docker_image
        image: cimg/go:1.15.2
        environment:
          <<: *environment

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run: make release
      - run: make docker-smoke-test
      - store_artifacts:
          path: dist/

  publish:
    docker:
      - <<: *release_docker_image

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run:
          name: Releasing and publishing
          command: |
            make release
            if [ "$CIRCLE_PROJECT_REPONAME" = "ld-relay" ]; then
                docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
                make publish
            fi
      - store_artifacts:
          path: dist/
