version: 2.1

experimental:
  notify:
    branches:
      only:
        - master

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.15
          docker-image: cimg/go:1.15.2
          run-lint: true
          test-coverage: true
      - go-test:
          name: Go 1.14
          docker-image: cimg/go:1.14.9
      - test-publish
      - publish:
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-.*)?/
            branches:
              only: /v\d+/
          requires:
            - Go 1.14
      
jobs:
  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
      test-coverage:
        type: boolean
        default: false
    
    docker:
      - image: <<parameters.docker-image>>
        environment: &environment
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts
          COMMON_GO_PACKAGES: >
            github.com/jstemmer/go-junit-report

    steps:
      - checkout
      - run: go get -u $COMMON_GO_PACKAGES
      - run: go version && go env
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_ARTIFACTS
      - unless:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests
                command: |
                  trap "go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml" EXIT
                  make test | tee $CIRCLE_ARTIFACTS/report.txt  
      - when:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests with coverage
                command: make test-coverage
            - run:
                name: Store coverage results
                command: cp build/coverage* /tmp/circle-artifacts
                when: always
      - run:
          name: Run Prometheus endpoint test
          command: ./scripts/test-prometheus-endpoint.sh
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts

  test-publish:
    docker:
      - &release_docker_image
        image: cimg/go:1.15.2
        environment:
          <<: *environment

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run: make release
      - run: make integration-test
      - store_artifacts:
          path: dist/

  publish:
    docker:
      - <<: *release_docker_image

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run:
          name: Releasing and publishing
          command: |
            make release
            if [ "$CIRCLE_PROJECT_REPONAME" = "ld-relay" ]; then
                docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
                make publish
            fi
      - store_artifacts:
          path: dist/
