version: 2.1

experimental:
  notify:
    branches:
      only:
        - master

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go 1.15
          docker-image: cimg/go:1.15.2
          run-lint: true
          test-coverage: true
      - go-test:
          name: Go 1.14
          docker-image: cimg/go:1.14.9
      - integration-test
      - test-publish
      - publish:
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-.*)?/
            branches:
              only: /v\d+/
          requires:
            - Go 1.14
      - dependency-scan:
          context: org-global
      
jobs:
  dependency-scan:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: bash <(curl --retry 5 -s -L https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss_agent.sh) -apiKey $WHITESOURCE_API_KEY -userKey $WHITESOURCE_USER_KEY -c ./.circleci/whitesource.cfg -d ~/ -project $CIRCLE_PROJECT_REPONAME -projectVersion $CIRCLE_BRANCH -logLevel debug
      - store_artifacts:
          path: ./whitesource
          destination: artifacts
  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
      test-coverage:
        type: boolean
        default: false
    
    docker:
      - image: <<parameters.docker-image>>
        environment: &environment
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts
          COMMON_GO_PACKAGES: >
            github.com/jstemmer/go-junit-report

    steps:
      - checkout
      - run: go get -u $COMMON_GO_PACKAGES
      - run: go version && go env
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_ARTIFACTS
      - unless:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests
                command: make test | tee $CIRCLE_ARTIFACTS/report.txt  
            - run:
                name: Process test results
                command: go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml
                when: always
      - when:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests with coverage
                command: make test-coverage
            - run:
                name: Store coverage results
                command: cp build/coverage* /tmp/circle-artifacts
                when: always
      - run:
          name: Run Prometheus endpoint test
          command: ./scripts/test-prometheus-endpoint.sh
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts

  integration-test:
    docker:
      - image: cimg/go:1.15.2
        environment: &environment
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts
          COMMON_GO_PACKAGES: >
            github.com/jstemmer/go-junit-report

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: go get -u $COMMON_GO_PACKAGES
      - run: go version && go env
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: Run integration tests
          command: make integration-test | tee $CIRCLE_ARTIFACTS/report.txt
      - run:
          name: Process test results
          command: go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml
          when: always
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts
        
  test-publish:
    docker:
      - &release_docker_image
        image: cimg/go:1.15.2
        environment:
          <<: *environment

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run: make release
      - run: make docker-smoke-test
      - store_artifacts:
          path: dist/

  publish:
    docker:
      - <<: *release_docker_image

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run:
          name: Releasing and publishing
          command: |
            make release
            if [ "$CIRCLE_PROJECT_REPONAME" = "ld-relay" ]; then
                docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
                make publish
            fi
      - store_artifacts:
          path: dist/
