version: 2.1

experimental:
  notify:
    branches:
      only:
        - v5
        - v6

workflows:
  workflow:
    jobs:
      - go-test:
          name: Go latest
          # This build has a deliberately unpinned version so that if a new Go major version
          # is released before we have updated the build, we can detect any problems early
          docker-image: circleci/golang:latest
          run-lint: true
          test-coverage: true
      - go-test:
          name: Go 1.16
          docker-image: cimg/go:1.16
      - go-test:
          name: Go 1.15
          docker-image: cimg/go:1.15
      - go-test:
          name: Go 1.14
          docker-image: cimg/go:1.14
      - benchmarks:
          docker-image: cimg/go:1.15
      - integration-test
      - test-publish
      - publish:
          filters:
            tags:
              only: /\d+\.\d+\.\d+(-.*)?/
            branches:
              only: /v\d+/
          requires:
            - Go 1.14
      - dependency-scan:
          context: org-global

  # Run hourly integration tests on the private v6 branch
  hourly-integration-test-stg:
    triggers:
    - schedule:
        cron: "0 * * * *"
        filters:
          branches:
            only: v6
    jobs:
      - integration-test
    when:
      equal: ["https://github.com/launchdarkly/ld-relay-private", <<pipeline.project.git_url>>]
  hourly-integration-test-prod:
    triggers:
    - schedule:
        cron: "0 * * * *"
        filters:
          branches:
            only: v6
    jobs:
      - integration-test:
          ld_base_url: https://app.launchdarkly.com
          ld_stream_url: https://stream.launchdarkly.com
          ld_sdk_url: https://sdk.launchdarkly.com
          ld_api_token_env_var: LD_API_TOKEN_PROD
    when:
      equal: ["https://github.com/launchdarkly/ld-relay-private", <<pipeline.project.git_url>>]

jobs:
  dependency-scan:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: bash <(curl --retry 5 -s -L https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss_agent.sh) -apiKey $WHITESOURCE_API_KEY -userKey $WHITESOURCE_USER_KEY -c ./.circleci/whitesource.cfg -d ~/ -project $CIRCLE_PROJECT_REPONAME -projectVersion $CIRCLE_BRANCH -logLevel debug
      - store_artifacts:
          path: ./whitesource
          destination: artifacts

  go-test:
    parameters:
      docker-image:
        type: string
      run-lint:
        type: boolean
        default: false
      test-coverage:
        type: boolean
        default: false
    
    docker:
      - image: <<parameters.docker-image>>
        environment: &environment
          CIRCLE_TEST_REPORTS: /tmp/circle-reports
          CIRCLE_ARTIFACTS: /tmp/circle-artifacts
          COMMON_GO_PACKAGES: >
            github.com/jstemmer/go-junit-report
          LD_TEST_REDIS: true
      - image: redis

    steps:
      - checkout
      - run: go get -u $COMMON_GO_PACKAGES
      - run: go version && go env
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: make lint
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_ARTIFACTS
      - unless:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests
                command: make test | tee $CIRCLE_ARTIFACTS/report.txt  
            - run:
                name: Process test results
                command: go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml
                when: always
      - when:
          condition: <<parameters.test-coverage>>
          steps:
            - run:
                name: Run tests with coverage
                command: make test-coverage
            - run:
                name: Store coverage results
                command: cp build/coverage* /tmp/circle-artifacts
                when: always
      - run:
          name: Run Prometheus endpoint test
          command: ./scripts/test-prometheus-endpoint.sh
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts

  integration-test:
    parameters:
      ld_base_url:
        type: string
        default: https://ld-stg.launchdarkly.com
      ld_stream_url:
        type: string
        default: https://stream-stg.launchdarkly.com
      ld_sdk_url:
        type: string
        default: https://sdk-stg.launchdarkly.com
      ld_api_token_env_var:
        type: string
        default: LD_API_TOKEN_STG
    machine: # can't use regular Docker mode because we need to run our own Docker containers and share files with them
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    environment:
      LD_BASE_URL: <<parameters.ld_base_url>>
      LD_STREAM_URL: <<parameters.ld_stream_url>>
      LD_SDK_URL: <<parameters.ld_sdk_url>>
      CIRCLE_TEST_REPORTS: /tmp/circle-reports
      CIRCLE_ARTIFACTS: /tmp/circle-artifacts
      COMMON_GO_PACKAGES: >
        github.com/jstemmer/go-junit-report
    steps:
      - checkout
      - run:
          name: install Go # since we're using machine mode, we can't use a preinstalled Go Docker image
          command: |
            sudo apt update
            sudo apt install -y software-properties-common
            sudo add-apt-repository -y ppa:longsleep/golang-backports
            sudo apt update
            sudo apt install -y golang-go
      - run: go version && go env
      - restore_cache:
          keys: 
            - deps-relay-i9ntest-{{ checksum "go.mod" }}    
      - run: go get -u $COMMON_GO_PACKAGES
      - run: go test -t integrationtests -i ./integrationtests # just install the dependencies for the tests
      - save_cache:
          key: deps-relay-i9ntest-{{ checksum "go.mod" }}    
          paths:
            - /home/circleci/.go_workspace
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS
          mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: Run integration tests
          command: LD_API_TOKEN=`echo $<<parameters.ld_api_token_env_var>>` make integration-test | tee $CIRCLE_ARTIFACTS/report.txt
      - run:
          name: Process test results
          command: go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml
          when: always
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts

  benchmarks:
    parameters:
      docker-image:
        type: string
    
    docker:
      - image: <<parameters.docker-image>>

    steps:
      - checkout
      - run: go version && go env
      - run:
          name: Run benchmarks
          command: make benchmarks

  test-publish:
    docker:
      - &release_docker_image
        image: cimg/go:1.15.13
        environment:
          <<: *environment

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run: make release
      - run: make docker-smoke-test
      - store_artifacts:
          path: dist/

  publish:
    docker:
      - <<: *release_docker_image

    steps:
      - checkout
      - setup_remote_docker  # start docker engine
      - run: sudo apt-get update
      - run: sudo apt-get install rpm
      - run:
          name: Releasing and publishing
          command: |
            make release
            if [ "$CIRCLE_PROJECT_REPONAME" = "ld-relay" ]; then
                docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
                make publish
            fi
      - store_artifacts:
          path: dist/
