repo:
  public: ld-relay
  private: ld-relay-private

template:
  name: go

releasableBranches:
  - name: v6
  - name: v5

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/ld-relay
    description: documentation
