repo:
  public: ld-relay
  private: ld-relay-private

circleci:
  linux:
    image: cimg/go:1.15.13
    context: org-global

template:
  name: go

releasableBranches:
  - name: v6
  - name: v5

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/ld-relay
    description: documentation
